/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgrammRouteImport } from './routes/programm'
import { Route as IndexRouteImport } from './routes/index'

const ProgrammRoute = ProgrammRouteImport.update({
  id: '/programm',
  path: '/programm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/programm': typeof ProgrammRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/programm': typeof ProgrammRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/programm': typeof ProgrammRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/programm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/programm'
  id: '__root__' | '/' | '/programm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProgrammRoute: typeof ProgrammRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programm': {
      id: '/programm'
      path: '/programm'
      fullPath: '/programm'
      preLoaderRoute: typeof ProgrammRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProgrammRoute: ProgrammRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
